config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email,  presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notive: "会員を登録しました。"
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to @user, notive: "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :users, notice: "会員登録を解除しました。"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav>
<label class="logo"><span class="logo-text-coin">Coin</span>Tract</label>
<input type="checkbox" id="check">
<label for="check" class="checkbtn">
  <i class="fas fa-align-justify"></i>   
</label>
 
<ul>
  <li><a href="#">Home</a></li>
  <li><a href="#">About</a></li>
  <li><a href="#">Services</a></li>
  <li><a href="#">Contact</a></li>
  <li><a href="#">Feedback</a></li>
</ul>
</nav>

app/views/users/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.email_field :email %>

app/views/users/edit.html.erb
<h1>Edit form</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |form| %>
  <%= render "form", f: form %>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<% if @users.present? %>
  <h1><%= @users[0].name %></h1>
  <h1><%= @users[0].email %></h1>
  <p>Find me in app/views/users/index.html.erb</p>
  
  <%= link_to "edit", edit_user_path(@users[0]) %>
  <%= link_to "destroy", user_path(@users[0]), method: :delete, data: { confirm: "本当に登録を解除しますか？" } %>
<% end %>

<%= link_to "new", :new_user %>

app/views/users/new.html.erb
<h1>Create form</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |form| %>
  <%= render "form", f: form %>
  <%= form.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>